// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/accessibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accessibility">> = Specific
  const handler = {} as typeof import("../../src/app/accessibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/resident/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/resident">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/resident/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/resident/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/resident/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/resident/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/resident/refunds/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/resident/refunds/[orderId]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/resident/refunds/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vendor/disputes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendor/disputes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vendor/disputes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vendor/edit-listing/[listingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendor/edit-listing/[listingId]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vendor/edit-listing/[listingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vendor/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendor/orders">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vendor/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vendor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendor">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vendor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vendor/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendor/payments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vendor/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vendor/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendor/refunds">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vendor/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vendor/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendor/register">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vendor/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/vendor/upgrade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendor/upgrade">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/vendor/upgrade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forums/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forums/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/forums/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forums/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forums">> = Specific
  const handler = {} as typeof import("../../src/app/forums/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policy">> = Specific
  const handler = {} as typeof import("../../src/app/policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vendors/[vendorId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendors/[vendorId]">> = Specific
  const handler = {} as typeof import("../../src/app/vendors/[vendorId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendors">> = Specific
  const handler = {} as typeof import("../../src/app/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vendors/profile/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendors/profile/edit">> = Specific
  const handler = {} as typeof import("../../src/app/vendors/profile/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
